name: Deploy Docusaurus

on:
  push:
    branches:
      - main  # ou a branch principal que você usa

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install

      - name: Build the website
        run: |
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages  # Cria a branch gh-pages se não existir
          git rm -rf .
          cp -r build/* .
          git add .
          git commit -m "Deploy Docusaurus"
          git push -f origin gh-pages
