name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main  # Aciona quando há um push na branch principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Etapa 1: Checar o código
      - name: Checkout code
        uses: actions/checkout@v2

      # Etapa 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Etapa 3: Instalar dependências
      - name: Install dependencies
        run: |
          cd ponderada  # Muda para o diretório correto
          npm install

      # Etapa 4: Build do Docusaurus
      - name: Build Docusaurus site
        run: |
          cd ponderada  # Certifique-se de estar no diretório correto
          npm run build

      # Etapa 5: Deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ponderada/build  # O diretório de build correto
